### ISSUE TITLE
Loopback Postgresql Array Type issue

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [loopbackio/loopback-next#4389]
We have a loopback 4 typescript model with below column

```
@property.array(String, {})
policy?: string[];
```

where in postgresql, we have given as 

```
policy TEXT[] 
```

which is an array type.

While storing this data in loopback Post method [create], it fails with following exceptions.

```
Unhandled error in POST /metrics: 500 error: malformed array literal: "["22129953825505","221602108611"]"
    at Connection.parseE (/Users/krish/opensense/services/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/Users/krish/opensense/services/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/Users/krish/opensense/services/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

The good thing is, the same works during update method. any help? We are finding complexities with loopback postgresql connector, where as many types [Array contains type] were not supported.

**Comment by bajtos** [comment]
Thank you @gopalakrishnan-subramani for reporting the issue. I don't know how well does our connector supports different ways how PostgreSQL can store arrays, this may be missing piece.

I think the conversion from a JavaScript array instance to SQL statement for setting an array value is handled by this code:

https://github.com/strongloop/loopback-connector-postgresql/blob/c0b7d3db4168cc6825a19780e646f44770b2568a/lib/postgresql.js#L626-L678

I don't see any special code for dealing with arrays, I think LoopBack simply calls `JSON.stringify` in such case.

Could you please check what happens when you configure the `policy` column as a string? (Is it `nvarchar` in PostgreSQL? I am not sure.) Will the problem go away?

**Comment by Jindu0506** [comment]
I am facing the very same problem while creating a record in postgres with postgres connector. Can anyone please help how to solve the issue?
