### ISSUE TITLE
Default filter in API Explorer for GET /todos of todo-list example produces a 500 error.

### ISSUE THREAD

**Issue by emonddr** [loopbackio/loopback-next#6641]
## Steps to reproduce

After starting the todo-list example, and then going into the API explorer, a default filter is available for the GET /todos endpoint. If the filter is used as-is, and the user presses the [Execute] button, the application returns

```json
{
  "error": {
    "statusCode": 500,
    "message": "Internal Server Error"
  }
}
```

and the stack trace shows:

```sh
Server is running at http://[::1]:3000
Request GET /todos?filter=%7B%0A%20%20%22offset%22%3A%200%2C%0A%20%20%22limit%22%3A%20100%2C%0A%20%20%22skip%22%3A%200%2C%0A%20%20%22where%22%3A%20%7B%0A%20%20%20%20%22additionalProp1%22%3A%20%7B%7D%0A%20%20%7D%2C%0A%20%20%22include%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22relation%22%3A%20%22string%22%2C%0A%20%20%20%20%20%20%22scope%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22offset%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22limit%22%3A%20100%2C%0A%20%20%20%20%20%20%20%20%22skip%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22where%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22additionalProp1%22%3A%20%7B%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22include%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22additionalProp1%22%3A%20%7B%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D failed with status code 500. Error: Invalid "filter.include" entries: {"relation":"string","scope":{"offset":0,"limit":100,"skip":0,"where":{"additionalProp1":{}},"include":[{"additionalProp1":{}}]}}
    at Object.includeRelatedModels (/Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/repository/dist/relations/relation.helpers.js:70:21)
    at TodoRepository.includeRelatedModels (/Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/repository/dist/repositories/legacy-juggler-bridge.js:389:28)
    at TodoRepository.find (/Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/repository/dist/repositories/legacy-juggler-bridge.js:286:21)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/rest/dist/providers/invoke-method.provider.js:40:32
    at async /Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/express/dist/middleware-interceptor.js:82:25
    at async /Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/express/dist/middleware-interceptor.js:82:25
    at async /Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/rest/dist/providers/send.provider.js:39:32
    at async MiddlewareSequence.handle (/Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/rest/dist/sequence.js:201:9)
    at async HttpHandler._handleRequest (/Users/dremond/Documents/PRs_LoopBack/authTwo/loopback-next/packages/rest/dist/http-handler.js:69:9)

```

If the user instead clears this default filter, the operation works.

## Current Behavior

In the API explorer (essentially Swagger UI), default `examples` of JSON  are given for input data and `filter` and `where` objects.

If these default examples (based on open api spec definitions) are mean to be a `general idea` of what can be specified by the user , but not intended as actual data, then perhaps there is no bug here at all.  Users are expected to enter JSON data that actually make sense for their application.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
By reading the error message, it seems that `"include":[{"additionalProp1":{}}]` is invalid.

```
Error: Invalid "filter.include" entries: {"relation":"string","scope":{"offset":0,"limit":100,"skip":0,"where":{"additionalProp1":{}},"include":[{"additionalProp1":{}}]}}
```

**Comment by emonddr** [comment]
Yeah I realize that. Is it the swagger UI (Api explorer) code that produces this sample filter?

**Comment by raymondfeng** [comment]
The sample request is probably from the openapi spec that we generate. Can you confirm? If so, we need to fix the root cause (invalid sample data for the filter/include schema).
