### ISSUE TITLE
Unable to migrate PostgreSQL

### ISSUE THREAD

**Issue by mbnoimi** [loopbackio/loopback-next#6876]
## Steps to reproduce

1. Run `lb4 discover` for creating the models
2. Run `lb4 repository` then created two controllers `lb4 controller lists todos`
3. Fixed the generated ids (related to bug #4557)
4. Created a simple relation (hasMany) `lb4 relation Lists` 
5. Added `await app.migrateSchema();` for igniting auto-update
6. Run `npm start` then get an error.

## Current Behavior

```
$ npm start

> Qtodo@0.0.1 prestart /home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo
> npm run rebuild


> Qtodo@0.0.1 rebuild /home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo
> npm run clean && npm run build


> Qtodo@0.0.1 clean /home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo
> lb-clean dist *.tsbuildinfo .eslintcache


> Qtodo@0.0.1 build /home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo
> lb-tsc


> Qtodo@0.0.1 start /home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo
> node -r source-map-support/register .

Cannot start the application. { error: syntax error at or near "undefined"
    at Parser.parseErrorMessage (/home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.stream.on (/home/mbnoimi/Snippets/JavaScript/LoopBack/Qtodo/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 98,
  name: 'error',
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '64',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Qtodo@0.0.1 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Qtodo@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mbnoimi/.npm/_logs/2020-12-05T09_15_48_805Z-debug.log
```

## Expected Behavior

Run smoothly because I didn't modify anything in the models

## Link to reproduction sandbox

https://github.com/mbnoimi/Qtodo/commit/76c8ae0930a670507a37258295c9ceff4c252087

## Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 10.19.0
```
```
$ npm ls --prod --depth 0 | grep loopback
├── @loopback/boot@3.1.1
├── @loopback/core@2.13.0
├── @loopback/repository@3.2.1
├── @loopback/rest@9.1.0
├── @loopback/rest-explorer@3.0.4
├── @loopback/service-proxy@3.0.4
├── loopback-connector-postgresql@5.2.1
```

**Comment by dhmlau** [comment]
@mbnoimi, the error seems to be coming from the `character varying` datatype of the `title` property:
```
  @property({
    type: 'string',
    required: true,
    postgresql: {columnName: 'title', dataType: 'character varying', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO'},
  })
  title: string;
```

I haven't got a chance to dig into why the `pg` module (or its dependency) is giving parse error for that datatype.

**Comment by mbnoimi** [comment]
> I haven't got a chance to dig into why the pg module (or its dependency) is giving parse error for that datatype.

Do you advise me to use MariaDB/MySQL instead? 
I'm struggling with LoopBack 4 & PostgreSQL (there are many unsolved bugs since a while)

**Comment by pktippa** [comment]
@mbnoimi this is not necessarily LoopBack or connector issue, I went through your code, the bug is in model property configuration.

for 'character varying' dataType, we need to specify dataLength key as well 
```ts
export class Lists extends Entity {
   ...
  
  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'title',
      dataType: 'character varying',
      dataLength: 20, // change here to required length
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  title: string;
}
```

```ts
export class Todos extends Entity {
  ...
  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'title',
      dataType: 'character varying',
      dataLength: 20, // change here to required length
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  title: string;
}
```

and also the model cannot have same named properties, even via configuration. Ex:


```ts
export class Todos extends Entity {
  ...
 @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'list_id', // the column is same as below property
      dataType: 'uuid',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  listId: string;

   // comment below property
   @property({
     type: 'string',
   })
   list_id?: string;
}
```
cc @dhmlau

**Comment by mbnoimi** [comment]
@pktippa You forgot something very important I mentioned at the top of the issue. I said:
> Run lb4 discover for creating the models

This mean I didn't make any mistake in the models because I didn't write them in the first place; `lb4 discover` generated the models which means there is a bug in `lb4 discover`

**Comment by pktippa** [comment]
Ah, my bad. The 'sql' folder has the DB which is used for `lb4 discover` ?

**Comment by pktippa** [comment]
The issue is in [loopback-connector-postgresql\lib\discovery buildQueryColumns](https://github.com/strongloop/loopback-connector-postgresql/blob/463becbce7c446a9d865b85e0513d93fd6374190/lib/discovery.js#L166-L185).

The query returns the `dataLength` as null, which is causing the issue during migrate.

![image](https://user-images.githubusercontent.com/7558577/101770021-d939f580-3b0d-11eb-95e2-7e67507765a8.png)
