### ISSUE TITLE
Add Node.js 15 to the build/test matrix

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#6977]
This is a follow-up for #5110, where we configured CI builds to run on GitHub Actions but did not manage to pass the tests on Node.js 15.

Based on https://github.com/strongloop/loopback-next/pull/5110#issuecomment-755198271, it looks like SQLite package is not correctly installed.

In the past, we had to downgrade npm to v6 when testing on Node.js 15 (see #6897), perhaps that's something to apply in our GitHub Actions setup too?

---

Cross-posting the test failures:

```
   4 failing

   1) TypeORM connection booter integration tests
        boots connections when app.boot() is called:
      DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
       at new DriverPackageNotInstalledError (extensions/typeorm/src/error/DriverPackageNotInstalledError.ts:8:9)
       at SqliteDriver.loadDependencies (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:135:19)
       at new SqliteDriver (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:49:14)
       at DriverFactory.create (extensions/typeorm/src/driver/DriverFactory.ts:43:24)
       at new Connection (extensions/typeorm/src/connection/Connection.ts:128:43)
       at ConnectionManager.create (extensions/typeorm/src/connection/ConnectionManager.ts:64:28)
       at TypeOrmApp.connection (extensions/typeorm/dist/typeorm.mixin.js:7:545)
       at TypeOrmConnectionBooter.load (extensions/typeorm/dist/typeorm-connection.booter.js:15:833)
       at Bootstrapper.boot (packages/boot/dist/bootstrapper.js:48:356)
       at TypeOrmApp.boot (packages/boot/src/mixins/boot.mixin.ts:63:87)
       at Context.<anonymous> (extensions/typeorm/src/__tests__/integration/booter.integration.ts:21:5)

   2) REST with TypeORM (integration)
        "before each" hook: getAppAndClient for "creates an entity":
      DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
       at new DriverPackageNotInstalledError (extensions/typeorm/src/error/DriverPackageNotInstalledError.ts:8:9)
       at SqliteDriver.loadDependencies (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:135:19)
       at new SqliteDriver (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:49:14)
       at DriverFactory.create (extensions/typeorm/src/driver/DriverFactory.ts:43:24)
       at new Connection (extensions/typeorm/src/connection/Connection.ts:128:43)
       at ConnectionManager.create (extensions/typeorm/src/connection/ConnectionManager.ts:64:28)
       at TypeOrmApp.connection (extensions/typeorm/dist/typeorm.mixin.js:7:545)
       at TypeOrmConnectionBooter.load (extensions/typeorm/dist/typeorm-connection.booter.js:15:833)
       at Bootstrapper.boot (packages/boot/dist/bootstrapper.js:48:356)
       at TypeOrmApp.boot (packages/boot/src/mixins/boot.mixin.ts:63:87)
       at Context.getAppAndClient (extensions/typeorm/src/__tests__/integration/rest.integration.ts:74:5)

   3) REST with TypeORM (integration)
        "after each" hook for "creates an entity":

       AssertionError [ERR_ASSERTION]: Cannot stop the application as it is booting.
       + expected - actual

       -false
       +true

       at TypeOrmApp.assertNotInProcess (packages/core/dist/application.js:110:96)
       at TypeOrmApp.stop (packages/core/dist/application.js:159:252)
       at Context.<anonymous> (extensions/typeorm/src/__tests__/integration/rest.integration.ts:26:24)
       at processImmediate (node:internal/timers:463:21)

   4) TypeORM connection booter unit tests
        binds connections during the load phase:
      DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
       at new DriverPackageNotInstalledError (extensions/typeorm/src/error/DriverPackageNotInstalledError.ts:8:9)
       at SqliteDriver.loadDependencies (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:135:19)
       at new SqliteDriver (extensions/typeorm/src/driver/sqlite/SqliteDriver.ts:49:14)
       at DriverFactory.create (extensions/typeorm/src/driver/DriverFactory.ts:43:24)
       at new Connection (extensions/typeorm/src/connection/Connection.ts:128:43)
       at ConnectionManager.create (extensions/typeorm/src/connection/ConnectionManager.ts:64:28)
       at AppUsingTypeOrm.connection (extensions/typeorm/dist/typeorm.mixin.js:7:545)
       at TypeOrmConnectionBooter.load (extensions/typeorm/dist/typeorm-connection.booter.js:15:833)
       at Context.<anonymous> (extensions/typeorm/src/__tests__/unit/booter.unit.ts:97:22)
```

**Comment by achrinza** [comment]
Closing as Node v16 is in the test matrix
