### ISSUE TITLE
Connection Pooling on MongoDB

### ISSUE THREAD

**Issue by bala-fashiondx** [loopbackio/loopback-next#7014]
We are using loopback-connector-mongodb@5.0.1 version to connect to mongo db . Our database admins are reporting that our application is using more connections and it is constantly growing. When they report issues , we just restart our applications and connection use count drops drastically (from 800 active connections to 500 connections on mongodb).

We need to implement connection pooling in loopback, but not sure on what settings needs to be done on the datasource.json file. Can you please give some suggestions.

**Comment by dhmlau** [comment]
Have you tried to use the settings in https://docs.mongodb.com/manual/reference/connection-string/index.html#connection-pool-options? LoopBack would just pass the configs to the mongodb node.js driver.

**Comment by bala-fashiondx** [comment]
I have tried this , but still facing the mongo db connection time out . The error that i am getting was ,

**Datasource mongo fails to connect due to timeout - aborting method 
"stack":"Error: Timeout in connecting after 5000 ms\n    at Timeout._onTimeout (/home/balu/fashiondx/bespoke/fdx-shopper-management-service/node_modules/loopback-datasource-juggler/lib/datasource.js:2617:10)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","level":"error","message":"Timeout in connecting after 5000 ms","timestamp":"2021-01-18 06:35:33"**

**Comment by dhmlau** [comment]
By looking at the error you posted above, it seems like the connection is invalid? If you remove the connection pool related config properties, did it complain the same thing?

**Comment by bala-fashiondx** [comment]
yes . There was same results even pool related config was there or not . The service working fine for few minutes . If the request to service increase I can able see the number of connections increasing in mongodb. But even after the response send , the connections were not closing in mongodb . It goes on increasing..

**Comment by vinutha93bnvs** [comment]
I have similar issue and looking for some solutions. 

Had a issue reported few days back, 
Refer https://github.com/strongloop/loopback-next/issues/7012
