### ISSUE TITLE
Login error: cannot read status of undefined on reject.provider.ts

### ISSUE THREAD

**Issue by A-Corregidor** [loopbackio/loopback-next#7602]
## Summary
We've some project working, with authentication and RBAC through Casbin, everything is OK
No files where changed, but after one npm install, login becomes broken with the following error: 
`Request POST /api/login failed with status code 500. TypeError: Cannot read property 'status' of undefined
    at MySequence.reject (********/node_modules/@loopback/rest/src/providers/reject.provider.ts:29:16)
    at MySequence.handle (********/src/sequence.ts:62:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HttpHandler._handleRequest (********/node_modules/@loopback/rest/src/http-handler.ts:115:5)
`

It seems that some libraries were updated and broke our login. Everything else is working fine, and already created tokens are still valid, we just can't create new tokens

The line where it fails (reject.provider.ts:29:16) is this, being err = undefined
`if (!err.status && !err.statusCode && err.code) {`

Content of sequence.ts
```

import { inject, Setter } from '@loopback/context';
import {
	FindRoute,
	InvokeMethod,
	ParseParams,
	Reject,
	RequestContext,
	RestBindings,
	Send,
	SequenceHandler,
	InvokeMiddleware,
} from '@loopback/rest';
import {
	AuthenticationBindings,
	AuthenticateFn,
	AUTHENTICATION_STRATEGY_NOT_FOUND,
	USER_PROFILE_NOT_FOUND,
} from '@loopback/authentication';

const SequenceActions = RestBindings.SequenceActions;

export class MySequence implements SequenceHandler {
	@inject(SequenceActions.INVOKE_MIDDLEWARE, { optional: true })
	protected invokeMiddleware: InvokeMiddleware = () => false;
	constructor(
		@inject(SequenceActions.FIND_ROUTE) protected findRoute: FindRoute,
		@inject(SequenceActions.PARSE_PARAMS) protected parseParams: ParseParams,
		@inject(SequenceActions.INVOKE_METHOD) protected invoke: InvokeMethod,
		@inject(SequenceActions.SEND) public send: Send,
		@inject(SequenceActions.REJECT) public reject: Reject,
		@inject(AuthenticationBindings.AUTH_ACTION)
		protected authenticateRequest: AuthenticateFn,
	) {}

	async handle(context: RequestContext) {
		try {
			const { request, response } = context;
			const finished = await this.invokeMiddleware(context);
			if (finished) return;
			const route = this.findRoute(request);

			const args = await this.parseParams(request, route);
			const result = await this.invoke(route, args);

				this.send(response, result);
		} catch (err) {
			if (err && (err.code === AUTHENTICATION_STRATEGY_NOT_FOUND || err.code === USER_PROFILE_NOT_FOUND)) {
				Object.assign(err, { statusCode: 401 /* Unauthorized */ });
			}
			this.reject(context, err);
			return;
		}
	}
}
```

Content of package.json
```
{
  "name": ********,
  "version": "1.0.0",
  "description": ********,
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": "14.15.5"
  },
  "scripts": {
   ************************
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src",
    "!*/__tests__"
  ],
  "dependencies": {
    "@loopback/authentication": "^7.3.1",
    "@loopback/authentication-jwt": "^0.9.1",
    "@loopback/authorization": "^0.6.4",
    "@loopback/boot": "^3.4.1",
    "@loopback/context": "^3.9.4",
    "@loopback/core": "^2.16.1",
    "@loopback/openapi-v3": "^3.4.7",
    "@loopback/repository": "^3.7.0",
    "@loopback/rest": "^9.3.1",
    "@loopback/rest-explorer": "^3.3.1",
    "@loopback/service-proxy": "^3.2.1",
    "@types/bcryptjs": "^2.4.2",
    "@types/multer": "^1.4.3",
    "@types/validator": "^13.6.0",
    "axios": "^0.21.1",
    "bcryptjs": "^2.4.3",
    "casbin": "^5.1.2",
    "casbin-sequelize-adapter": "^2.1.0",
    "cheerio": "^1.0.0-rc.3",
    "http-errors": "^1.8.0",
    "isemail": "latest",
    "jsonwebtoken": "^8.5.1",
    "jsrsasign": "^10.2.24",
    "log-timestamp": "^0.3.0",
    "loopback-connector-mongodb": "^5.2.3",
    "loopback-connector-mysql": "^5.4.4",
    "luxon": "^1.25.0",
    "multer": "^1.4.2",
    "mysql2": "^2.1.0",
    "node-forge": "^0.10.0",
    "node-rsa": "^1.0.7",
    "nodemon": "^2.0.2",
    "request": "^2.88.2",
    "stream-json": "^1.7.1",
    "tedious": "^11.0.5",
    "uuid": "^7.0.2",
    "winston": "^3.2.1",
    "xml-crypto": "^1.4.0",
  },
  "devDependencies": {
    "@loopback/build": "^6.4.1",
    "@loopback/eslint-config": "^10.2.1",
    "@loopback/testlab": "^3.4.1",
    "@types/luxon": "^1.26.3",
    "@types/node": "^10.17.60",
    "@types/uuid": "^7.0.2",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "eslint": "^7.29.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-eslint-plugin": "^2.2.1",
    "eslint-plugin-mocha": "^7.0.0",
    "eslint-plugin-prettier": "^3.1.2",
    "prettier": "2.3.2",
    "source-map-support": "^0.5.19",
    "typescript": "~4.0.7"
  }
}
```

## Steps to reproduce
Being some production code, I cant place it here and I couldn't reproduce it in an example-based sandbox.
I know this could be some poor information, I'll try to show you everything you ask (and I can) to find where the problem is

## Current Behavior
When sending a legit POST Login request (if login params are not correct, an 401 is raised as expected), an exception is caught.

## Expected Behavior
Login should return a token as usual

## Additional information
linux x64 14.17.1
├── @loopback/authentication@7.3.1
├── @loopback/authentication-jwt@0.9.1
├── @loopback/authorization@0.6.6
├── @loopback/boot@3.4.1
├── @loopback/context@3.16.0
├── @loopback/core@2.16.1
├── @loopback/openapi-v3@3.4.9
├── @loopback/repository@3.7.0
├── @loopback/rest@9.3.1
├── @loopback/rest-explorer@3.3.1
├── @loopback/service-proxy@3.2.1
├── loopback-connector-mongodb@5.5.0
├── loopback-connector-mysql@5.4.4

**Comment by Habbiton** [comment]
Any tips on this?

**Comment by A-Corregidor** [comment]
Any tips on this?

**Comment by achrinza** [comment]
Does https://github.com/strongloop/loopback-next/pull/7491 solve the issue?

**Comment by A-Corregidor** [comment]
Any tips?

**Comment by achrinza** [comment]
I'll proceed to close the issue due to inactivity; Please don't hesitate to ping me to re-open the issue if the problem persists.
