### ISSUE TITLE
Failure during boot phase @loopback/metadata

### ISSUE THREAD

**Issue by michaelerobertsjr** [loopbackio/loopback-next#8295]
### Describe the bug

We had designed a LB4 application with a microservices architecture but have decided to refactor it into one repository/app. When we pulled in the front-end code we can get it to build both the front end and compile and build the LB4 backend, but we are unable to determine why we are getting an error during the `start` process.

We can see it successfully passes the `boot()` phase, but somewhere in the `start()` seemingly related to data sources, we receive an uncaught exception and it terminates.

### Logs

```shell
Stack trace after running an `npm run start`:

Cannot start the application. TypeError:
    at Reflect.getMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/reflect-metadata/Reflect.js:354:23)
    at NamespacedReflect.getMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/metadata/src/reflect.ts:49:20)
    at Function.getClassMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/metadata/src/inspector.ts:66:19)
    at isModel (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:27:23)
    at reduceSpecContent (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:54:9)
    at Array.reduce (<anonymous>)
    at reduceSpecResponses (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:88:49)
    at Array.reduce (<anonymous>)
    at buildResponsesFromMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:149:57)
    at resolveControllerSpec (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/controller-spec.ts:211:51)
    at getControllerSpec (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/controller-spec.ts:531:12)
    at RestServer._createHttpHandler (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:444:40)
    at RestServer._setupHandlerIfNeeded (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:416:10)
    at RestServer.start (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:975:10)
    at invokeTargetMethod (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/context/src/invocation.ts:263:47)
    at /Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/context/src/invocation.ts:240:12
```
```


### Additional information

_No response_

### Reproduction

The provided stack trace indicates it is loopback core code, not our controllers or models.

**Comment by achrinza** [comment]
Thanks for opening an issue; I've tested around to see if I was able to replicate the issue, but unfortunately I was not able to reproduce.emitMetat

Since it seems like its caused after an attempted integration with a separate codebase, I suspect that the `tsconfig` was changed as well?

It believe that might be the issue as LoopBack 4's dependency injection framework depends on `reflect-metadata`, which in turn depends on `emitDecoratorMetadata`.

**Comment by achrinza** [comment]
Closing due to inactivity. Feel free to request to re-open or open a new issue if the problem persists.

**Comment by savan-thakkar** [comment]
Facing same issue with lb4 (only backend code) pls let me know if any solution is there

**Comment by balbertho** [comment]
> ### Describe the bug
> We had designed a LB4 application with a microservices architecture but have decided to refactor it into one repository/app. When we pulled in the front-end code we can get it to build both the front end and compile and build the LB4 backend, but we are unable to determine why we are getting an error during the `start` process.
> 
> We can see it successfully passes the `boot()` phase, but somewhere in the `start()` seemingly related to data sources, we receive an uncaught exception and it terminates.
> 
> ### Logs
> ```shell
> Stack trace after running an `npm run start`:
> 
> Cannot start the application. TypeError:
>     at Reflect.getMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/reflect-metadata/Reflect.js:354:23)
>     at NamespacedReflect.getMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/metadata/src/reflect.ts:49:20)
>     at Function.getClassMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/metadata/src/inspector.ts:66:19)
>     at isModel (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:27:23)
>     at reduceSpecContent (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:54:9)
>     at Array.reduce (<anonymous>)
>     at reduceSpecResponses (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:88:49)
>     at Array.reduce (<anonymous>)
>     at buildResponsesFromMetadata (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/build-responses-from-metadata.ts:149:57)
>     at resolveControllerSpec (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/controller-spec.ts:211:51)
>     at getControllerSpec (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/openapi-v3/src/controller-spec.ts:531:12)
>     at RestServer._createHttpHandler (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:444:40)
>     at RestServer._setupHandlerIfNeeded (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:416:10)
>     at RestServer.start (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/rest/src/rest.server.ts:975:10)
>     at invokeTargetMethod (/Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/context/src/invocation.ts:263:47)
>     at /Users/michaelrobertsjr/projects/hexis/hexis-core-api/node_modules/@loopback/context/src/invocation.ts:240:12
> ```
> 
> ```
> 
> 
> ### Additional information
> 
> _No response_
> 
> ### Reproduction
> 
> The provided stack trace indicates it is loopback core code, not our controllers or models.
> ```

@michaelerobertsjr 
Hi, I came across the same issue today after running "lb4 update". And after debug, I found out that an API endpoint is undefined for responseModelOrSpec and it turns out that the endpoint has not defined the "schema" variable, and in my case it is "Schema" instead, after changing it back to correct case, the issue is resolved.

![image](https://user-images.githubusercontent.com/12370920/194522676-3b210a8a-419c-4cdc-ae64-3785c0bc11ed.png)

@savan-thakkar
Your case seems a bit different from ours, maybe with different versions of packages, you can try debugging to find out which schema is causing problem.
