### ISSUE TITLE
Creating app fails while installing @eslint/eslintrc: No matching version.

### ISSUE THREAD

**Issue by snspinn** [loopbackio/loopback-next#8401]
### Describe the bug

Creating an project/app with the `lb4` cli, using all the default settings when creating the project. It fails with `No matching version found for @eslint/eslintrc@^1.2.1.`

If I try to run the application with `npm start` it fails at with `sh: 1: lb-clean: not found`.

### Software versions
nvm: 0.39.1
node: v16.14.0
npm: 8.3.1

### Trying to run the API
```
ubuntu@ubuntu:~/my-general-api/general-api$ npm start

> general-api@0.0.1 prestart
> npm run rebuild


> general-api@0.0.1 rebuild
> npm run clean && npm run build


> general-api@0.0.1 clean
> lb-clean dist *.tsbuildinfo .eslintcache

sh: 1: lb-clean: not found
```

### Logs

```shell
...
...
2241 timing command:install Completed in 7621ms
2242 verbose type range
2243 verbose stack @eslint/eslintrc: No matching version found for @eslint/eslintrc@^1.2.1.
2243 verbose stack     at module.exports (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
2243 verbose stack     at /home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
2243 verbose stack     at async Promise.all (index 22)
2243 verbose stack     at async Arborist.[buildDepStep] (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1051:5)
2243 verbose stack     at async Arborist.buildIdealTree (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
2243 verbose stack     at async Promise.all (index 1)
2243 verbose stack     at async Arborist.reify (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
2243 verbose stack     at async Install.exec (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/lib/commands/install.js:157:5)
2243 verbose stack     at async module.exports (/home/ubuntu/.nvm/versions/node/v16.14.0/lib/node_modules/npm/lib/cli.js:66:5)
2244 verbose cwd /home/ubuntu/ek-general-api-lb4/general-api
2245 verbose Linux 5.4.0-104-generic
2246 verbose argv "/home/ubuntu/.nvm/versions/node/v16.14.0/bin/node" "/home/ubuntu/.nvm/versions/node/v16.14.0/bin/npm" "install" "--cache-min" "86400"
2247 verbose node v16.14.0
2248 verbose npm  v8.3.1
2249 error code ETARGET
2250 error notarget No matching version found for @eslint/eslintrc@^1.2.1.
2251 error notarget In most cases you or one of your dependencies are requesting
2251 error notarget a package version that doesn't exist.
2252 verbose exit 1
2253 timing npm Completed in 7889ms
2254 verbose unfinished npm timer reify 1647449876245
2255 verbose unfinished npm timer reify:loadTrees 1647449876260
2256 verbose code 1
2257 error A complete log of this run can be found in:
2257 error     /home/ubuntu/.npm/_logs/2022-03-16T16_57_55_990Z-debug-0.log
```

### Additional information

I managed to work around/solve the problem by running `npm install --save --legacy-peer-deps` in the project's root folder. After this it will build and run ok.

### Reproduction

none

**Comment by snspinn** [comment]
## Update

After deleting the entire lb4 generated directory, I could rebuild the project without coming across the issue again. 

At this time I'm not sure if it was the version of lb4 I was using : I foolishly ran `lb4 update` before confirming the installed version and, since I'm not familiar with what to expect from the `lb4 update` output, I'm not sure if I was running an older version before the 'update'.

Currently using version 3.1.1 without issue.

Going to close this as I have nothing more to report, and the issue seems to be fixed.
