### ISSUE TITLE
cant discover

### ISSUE THREAD

**Issue by z976807015** [loopbackio/loopback-next#9291]
### Describe the bug

i lb4 discover 
show:
----------------------------------------------------------------------------------------------
✖ An error occured while running loopback4:discover#loadAllDatasources
  const val = new ds[key]();
              ^

TypeError: ds[key] is not a constructor
    at Object.loadDataSource (E:\nvm\v19.0.1\node_modules\@loopback\cli\lib\model-discoverer.js:49:15)
    at E:\nvm\v19.0.1\node_modules\@loopback\cli\generators\discover\index.js:123:23
    at Array.map (<anonymous>)
------------------------------------------------------------------------------------------------

### Reproduction

no

**Comment by z976807015** [comment]
This problem has occurred since the database has a table with more than two million rows of data
