### ISSUE TITLE
lb4 openapi generated routes fail to work without servers field

### ISSUE THREAD

**Issue by aaqilniz** [loopbackio/loopback-next#9363]
### Describe the bug

While accessing the routes created with lb4 openapi, the app throws the following error: 

`Request GET /v3.1/all?fields=name failed with status code 500. TypeError: Only absolute URLs are supported`. 

This happens because the specs don't have a servers field or don't contain absolute URLs.

The docs suggest to download the specification locally and then generating the routes with lb4 openapi. 

The loopback should work without needing to download the specs and shouldn't need a user to download the specification. 

Is it possible to make the loopback app work even if the servers field is not provided or is not an absolute path? 
Can we achieve this by adding a servers field in the framework before processing the request?

### Logs

```shell
Request GET /v3.1/all?fields=name failed with status code 500. TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/media/<path>/testing-cache-package/node_modules/node-fetch/lib/index.js:1327:9)
    at /media/<path>/testing-cache-package/node_modules/node-fetch/lib/index.js:1454:19
    at new Promise (<anonymous>)
    at fetch (/media/<path>/testing-cache-package/node_modules/node-fetch/lib/index.js:1451:9)
    at Function.http (/media/<path>/testing-cache-package/node_modules/swagger-client/lib/http/index.js:82:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Reproduction

https://github.com/aaqilniz/testing-cache-package/tree/issue-absoulte-url

**Comment by aaqilniz** [comment]
Hi @samarpanB. Sorry for tagging you here too. But can you provide you suggestions on the issue?

**Comment by aaqilniz** [comment]
I think I am misunderstanding the situation. This issue is being generated from node-fetch. That too I think is not an issue. It requires to have absolute URLs.

**Comment by aaqilniz** [comment]
Fixed with [this](https://github.com/loopbackio/loopback-connector-openapi/pull/31) PR
